const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94713424265"
const SESSION_ID = "PRABATH-MD~PIlwTTAB#-e9If6WR7JJJWXssH2OlVoVZO0Ecp-PncXrUdAzyhc4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
